# Generated by Django 4.1.5 on 2023-01-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='dissertation',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='d_app.client')),
                ('topic', models.TextField(blank=True, null=True)),
                ('tech', models.CharField(choices=[('web application', 'web application'), ('desktop application', 'desktop application'), ('mobile application', 'mobile application')], max_length=50)),
                ('tech_stack', models.CharField(choices=[('artificial intelligence', 'artificial intelligence'), ('machine learning', 'machine learning')], max_length=50)),
            ],
        ),
    ]
