# Generated by Django 4.1.5 on 2023-01-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_app', '0002_client_dissertation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='dissertation_option',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
