# Generated by Django 4.1.5 on 2023-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_app', '0003_dissertation_dissertation_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='tech',
            field=models.CharField(blank=True, choices=[('web application', 'web application'), ('desktop application', 'desktop application'), ('mobile application', 'mobile application')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='tech_stack',
            field=models.CharField(blank=True, choices=[('artificial intelligence', 'artificial intelligence'), ('machine learning', 'machine learning')], default='', max_length=50),
        ),
    ]
